spring.application.name=camica

# =========================
# PostgreSQL Config
# =========================
spring.datasource.url=jdbc:postgresql://localhost:5432/camica
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.hbm2ddl.auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Logging opcional
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


#JWT
jwt.secret=feSLZrm7QpEPMc3TY9B2erBaetvnuLny5dRUd9h4BBo
jwt.expiration=604800


#Email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sigeucorp@gmail.com
spring.mail.password=jacl efxy zgjh ccmj
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true